# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 26e0827d9ddfb92d86d26ea1ec93b839e19d33eb3965c1a08467d89423bbb7c4dbcd2fed9a6b6c7d6ae9c20c1cd7754c5b7bb63d2a743184db234ab525566498

test:
  secret_key_base: 067ec1cfe9f4f9e023852bd1f112c44beca31f75742e786275c7e0107fb0d2876967ae3b6d0cc09e1d2afe0cf1f7be4742926a9261a5666684528d77bf38734d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
